id: bb1d391c48af4c93bdf5daf7d6ea95ee
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_252-The_Fourfold_Accomplishment-v2
  language: bo
  author: ''
  volume: {}
